services:
  lamer_homepage:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.lamer_homepage.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.lamer_homepage.entrypoints=websecure"
      - "traefik.http.routers.lamer_homepage.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.lamer_homepage.middlewares=traefik-compress"
      - "traefik.http.services.lamer_homepage.loadbalancer.server.port=${PORT}"
    container_name: lamer_homepage
    command: npm run serve
    restart: unless-stopped
    networks:
      - "traefik"

networks:
  traefik:
    external: true
